[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install --extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/ -r requirements.txt"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port $PORT"
